version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: gdi
    ports:
      - 3306:3306
    expose:
      - 3306
volumes:
  data:
